### ISSUE TITLE
Add Contributors section in README.md

### ISSUE THREAD

**Issue by Vani177** [server-geeks/WebMine#42]
Hey, I think a "Contributors" section should be added in the readme.md file itself.
If you wish to allow me to create it please assign me this issue.
Thanks!

**Comment by mrkc2303** [comment]
Closing this issue as the similar PR has been merged.
Thanks for the Contribution.

**Comment by Vani177** [comment]
> Closing this issue as the similar PR has been merged. Thanks for the Contribution.
Glad to contribute!
